
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A AVANZAR CON DE DIRECCION ENTREGAR ESQUIVAR GOLPEAR HERRAMIENTA LLEVAR OBJETO RECOGER SALIRcomando : RECOGER OBJETOcomando : AVANZAR DIRECCIONcomando : LLEVAR OBJETOcomando : GOLPEAR CON HERRAMIENTAcomando : ENTREGAR OBJETO A OBJETO'
    
_lr_action_items = {'RECOGER':([0,],[2,]),'AVANZAR':([0,],[3,]),'LLEVAR':([0,],[4,]),'GOLPEAR':([0,],[5,]),'ENTREGAR':([0,],[6,]),'$end':([1,7,8,9,12,14,],[0,-1,-2,-3,-4,-5,]),'OBJETO':([2,4,6,13,],[7,9,11,14,]),'DIRECCION':([3,],[8,]),'CON':([5,],[10,]),'HERRAMIENTA':([10,],[12,]),'A':([11,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> RECOGER OBJETO','comando',2,'p_comando_recoger','cake_parser.py',6),
  ('comando -> AVANZAR DIRECCION','comando',2,'p_comando_avanzar','cake_parser.py',15),
  ('comando -> LLEVAR OBJETO','comando',2,'p_comando_llevar','cake_parser.py',19),
  ('comando -> GOLPEAR CON HERRAMIENTA','comando',3,'p_comando_golpear','cake_parser.py',26),
  ('comando -> ENTREGAR OBJETO A OBJETO','comando',4,'p_comando_entregar','cake_parser.py',34),
]
